"""Added language field to FAQ

Revision ID: 98353334602e
Revises: 9e56965d89b6
Create Date: 2025-02-01 22:01:21.344697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98353334602e'
down_revision: Union[str, None] = '9e56965d89b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faqs', sa.Column('language', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faqs', 'language')
    # ### end Alembic commands ###
